#!/usr/bin/env bash

# Ensure that any optional peer dependency (e.g. ReactTransitionGroup and
# ReactPopper) are properly set as optional globals. Specifically, do not
# error if the user has not loaded these dependencies. Degrade gracefully.

set -e

DIST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../dist" && pwd)"

# Note: Babebli transforms "global" into obfuscated/minified translated
# variable names. Typically these are [a-zA-Z].
sed -i -E 's#,([a-zA-Z]+)\.ReactTransitionGroup\.Transition#,\1.ReactTransitionGroup \&\& \1.ReactTransitionGroup.Transition || \{\}#' $DIST_DIR/reactstrap.min.js