#!/usr/bin/env bash

set -e

VERSION=$(node -p -e "require('./package.json').version")
CURRENT_BRANCH="$(git symbolic-ref --short -q HEAD)"

success() {
  echo -e "\033[32;1m$1"
}

error() {
  echo -e "\033[31;1m$1"
}

if [ -z "$TRAVIS" ]; then
  git checkout v4
  git pull
  npm install
  npm run build
fi

if [ -z "$GITHUB_TOKEN" ]; then
  error "Environment variable GITHUB_TOKEN does not exist. Stopping deploy."
  exit 1
fi

if [ -z "$CURRENT_BRANCH" ]; then
  error "Not in a branch. Stopping deploy."
  exit 1
fi

if [ -z "$VERSION" ]; then
  error "Unable to get current npm version of this package"
  exit 1
fi

if ! [ -z "$TRAVIS" ]; then
  git remote rm origin
  git remote add origin https://${GITHUB_TOKEN}@github.com/reactstrap/reactstrap.git > /dev/null 2>&1
  git config user.name "Travis-CI"
  git config user.email "reactstrap@github.io"
fi

git tag -a $VERSION -m "release $VERSION"
git push --set-upstream origin $CURRENT_BRANCH > /dev/null 2>&1
git push --tags > /dev/null 2>&1

success "pushed $VERSION tag to GitHub"
